platformName: Android

#模拟器
#platformVersion: 4.4.2
#deviceName: 127.0.0.1:62001

#真机
platformVersion: 8.0.0
deviceName: Nexus 6P
udid: 84B5T15A10000334

#piggy
appname: howbuy.android.piggy_68.apk
appPackage: howbuy.android.piggy
appActivity: com.howbuy.piggy.aty.AtyLauncher

#zsjj
#appname: howbuy.android.palmfund_169.apk
#appPackage: howbuy.android.palmfund
#appActivity: com.howbuy.fund.init.AtyEntry

noReset: True
unicodeKeyboard: True
resetKeyboard: True
ip: 127.0.0.1
port: 4723

